#!/bin/bash
# . "$_s/one_shots/vlc_to_lin"
# x_ "$_s/one_shots/vlc_to_lin"
$r_ _ iter

vlc_to_lin() {
    [[ $# -lt 1 ]] && {
        echo "Usage vlc_to_lin base_path"
        return
    }
    base_path="$1"
    update_xspf() {
        file_path="$1"
        file_dir_path="${file_path%\/*}"
        file_name="${file_path##*\/}"
        [[ "$file_name" =~ ^lin_ ]] && return
        if [[ "$file_name" =~ ^win_(.*)$ ]]; then
            out_file_path="$file_dir_path/lin_${BASH_REMATCH[1]}"
        else
            out_file_path="$file_dir_path/lin_$file_name"
        fi
        >"$out_file_path"
        IFS=""
        while IFS="" read -r line || [[ -n "$line" ]]; do
            [[ "$line" =~ ^(.*)file\:\/\/\/C\:\/s\/(.*)\<\/location\>.*$ ]] && {
                echo "${BASH_REMATCH[1]}file:///i/s/${BASH_REMATCH[2]}</location>" >>"$out_file_path"
                continue
            }
            echo "$line" >>"$out_file_path"
        done <"$file_path"
    }

    file_fn() {
        file_path="$1"
        [[ "$file_path" =~ \.xspf && ! "$file_path" =~ ^lin_ ]] && {
            ec2 "file_path xspf: '$file_path'"
            update_xspf "$file_path"
        }
    }
    if [[ -d "$base_path" ]]; then
        iter "$base_path" file_fn
    else
        update_xspf "$base_path"
    fi
}

vlc_to_lin "$@"
