#!/bin/bash
# . "$_s/one_shots/specific/vlc_to_lin"
# x_ "$_s/one_shots/specific/vlc_to_lin"

[[ $# -lt 1 ]] && {
    echo "Usage vlc_to_lin path1 ?path2 ..."
    return
}

# file:///C:/s to file:///i/s
for_each_file() {
    file_path="$1"
    file_dir_path="${file_path%\/*}"
    file_name="${file_path##*\/}"
    # skip wip && not xspf
    [[ "$file_name" =~ ^_ || ! "$file_name" =~ .xspf$ ]] && return
    # skip already lin
    [[ "$file_name" =~ ^lin_ ]] && return
    if [[ "$file_name" =~ ^win_(.*)$ ]]; then
        out_file_path="$file_dir_path/lin_${BASH_REMATCH[1]}"
    else
        out_file_path="$file_dir_path/lin_$file_name"
    fi
    >"$out_file_path"
    IFS=""
    while IFS="" read -r line || [[ -n "$line" ]]; do
        [[ "$line" =~ ^(.*)file\:\/\/\/C\:\/s\/(.*)\<\/location\>.*$ ]] && {
            echo "${BASH_REMATCH[1]}file:///i/s/${BASH_REMATCH[2]}</location>" >>"$out_file_path"
            continue
        }
        echo "$line" >>"$out_file_path"
    done <"$file_path"
}

for each_arg in "$@"; do
    if [[ -d "$each_arg" ]]; then
        $r_ _ iter
        iter "$each_arg" for_each_file
    else
        for_each_file "$each_arg"
    fi
done
