#!/bin/bash
# . $_t/com
# do not import directly, instead import the com module

export V_RED="\033[1;38;2;255;0;0m"
export GRAY='\033[1;30m'
export BLACK='\033[0;30m'
export B_WHITE="\033[1;38;2;255;255;255m"

export H_BLUE='\033[1;34m'
export L_BLUE='\033[1;36m'

export GREEN='\033[1;32m'
export L_GREEN='\033[1;29m'
export F_GREEN='\033[0;32m'
export F_RED='\033[0;31m'
export B_BLUE='\033[1;34m'
export L_BLUE='\033[0;34m'
export H_BLUE='\033[1;34m'
# export H_PURP='\033[1;35m'
export L_PURP='\033[0;35m'
export PURP='\033[1;35m'
export L_TIEL='\033[0;36m'
export H_TIEL='\033[1;36m'
# export TIEL='\033[1;36m'
export H_BLUE='\033[0;29m'
# export H_BLUE='\033[0;29m'
export I_RED='\033[0;41m'
export WHITE='\033[0;29m'
export H_WHITE='\033[1;29m'
export L_ORAN='\033[0;33m'
export H_ORAN='\033[1;33m'

export LILAC="\033[1;38;2;170;60;255m"
export COOL="\033[1;38;2;110;70;255m"
export ERROR='\033[1;41m'
export NOCOLOR='\033[0m'
export NOPE='\033[0m'
export NO='\033[0m'

# flag separators for echo where-ever
export f_0="- - - ~ - - - ~ - - - ~ "
export f_1="- - - ~"
export f_2=" ~ - - - ~"
# _down _up
export f_d="~ \|/\|/ ~"
export f_u="~ /|\/|\ ~"
_fd() {
    # echo "$f_1 $@ $f_2"
    ec "${f_0}\n${f_1} <$@>${f_2}\n$f_0"
}
_fu() {
    # echo "$f_1 $@ $f_2"
    ec "${f_it}\n${f_1} </$@> $f_u"
}
# begin section flag
_fb() {
    ec "$f_1 .<$@> $f_2"
}
# end section flag
_fe() {
    ec "$f_1 </$@> $f_2"
}
