#!/bin/bash
# $_t/util/welcome
. "$_t/util/colors_flags"

# this is required because we can't import .bashrc
PS1="${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "
# PS1="${debian_chroot:+($debian_chroot)}\u@\h:\w\$ "
# sleep 1 && {
echo -e "\n$LILAC$f_0\n$NOPE"
echo "_  _     _     .~"
echo "|  ^ ~   |"
echo "^        ^          ~.o"
echo "              ."
echo "      _"
echo "      ^ ~            ."
echo ""
echo -en "$LILAC$f_0\n${NOPE}"
# "${PS1@P}"
# }
