#!/bin/bash
https://github.com/ungoogled-software/ungoogled-chromium-windows/releases
https://github.com/VSCodium/vscodium/releases
https://git-scm.com/downloads
https://duckduckgo.com/?q=node+windows+11&ia=web

https://bitwarden.com/download/#downloads-desktop

# login then
https://my.nordaccount.com/downloads/nordvpn/
https://www.qbittorrent.org/download
https://www.videolan.org/vlc/download-windows.html

https://www.ungoogledextensions.com/
https://chromewebstore.google.com/detail/xkit-rewritten/ehgbadgnkmeeldglkmnplolneidgpbcm

# WIFI
# AAAF2D6AsKCxQe5Y