#!/bin/bash

# make a new blank repository in the current directory
git init

# add a remote
git remote add origin url://to/source/repository

# fetch a commit (or branch or tag) of interest
# Note: the full history up to this commit will be retrieved unless
#       you limit it with '--depth=...' or '--shallow-since=...'
git fetch origin \<sha1-of-commit-of-interest\>

# reset this repository's to the current commit of branch
git reset --hard FETCH_HEAD

# ?????????????????????????????
# reset this repository's master branch to the commit of interest
git reset --hard FETCH_HEAD
# or
git clone --depth=1 URL
git fetch --depth=1 origin SHA1
git checkout SHA1
git branch -D @{-1} # if you want to tidy up the fetched branch
